kubectl wait on all applies (#15)
* kubectl wait on all applies

* Added code to wait 4 minutes for development url

* Added code to wait 4 minutes for development url

* Added code to wait 4 minutes for development url

* Added code to wait 4 minutes for development url

diff --git a/.github/workflows/deployAWS.yml b/.github/workflows/deployAWS.yml
--- a/.github/workflows/deployAWS.yml
+++ b/.github/workflows/deployAWS.yml
@@ -91,37 +91,24 @@ jobs:
       - name: Update kube config
         run: aws eks update-kubeconfig --name ${{ env.EKS_NAME }} --region ${{ env.AWS_REGION }}
 
-      - name: Check if namespace exists
-        run: |
-          if [[ $(kubectl get namespace ${{ env.BRANCH }} --ignore-not-found=true) ]]; then
-            echo "CREATE_NAMESPACE=false" >> $GITHUB_ENV
-          else
-            echo "CREATE_NAMESPACE=true" >> $GITHUB_ENV
-          fi
-
       - name: Create namespace
         run: kubectl create namespace ${{ env.BRANCH }} --dry-run=client -o yaml | kubectl apply -f -
 
       - name: Deploy image to AWS EKS
         run: |
-          kubectl apply -f .kubernetes/qa/aws-auth.yaml
+          kubectl apply -f .kubernetes/qa/aws-auth.yaml --wait=true
 
-          kubectl apply -f .kubernetes/qa/postgres-config.yaml --namespace=${{ env.BRANCH }}
-          kubectl apply -f .kubernetes/qa/postgres-secret.yaml --namespace=${{ env.BRANCH }}
-          kubectl apply -f .kubernetes/qa/postgres.yaml --namespace=${{ env.BRANCH }}
+          kubectl apply -f .kubernetes/qa/postgres-config.yaml --namespace=${{ env.BRANCH }} --wait=true
+          kubectl apply -f .kubernetes/qa/postgres-secret.yaml --namespace=${{ env.BRANCH }} --wait=true
+          kubectl apply -f .kubernetes/qa/postgres.yaml --namespace=${{ env.BRANCH }} --wait=true
 
-          kubectl apply -f .kubernetes/qa/dynamodb.yaml --namespace=${{ env.BRANCH }}
+          kubectl apply -f .kubernetes/qa/dynamodb.yaml --namespace=${{ env.BRANCH }} --wait=true
 
-          kubectl apply -f .kubernetes/qa/s3.yaml --namespace=${{ env.BRANCH }}
+          kubectl apply -f .kubernetes/qa/s3.yaml --namespace=${{ env.BRANCH }} --wait=true
 
       - name: Create Webapp
         run: |
-          if [[ ${{ env.CREATE_NAMESPACE }} ]]; then
-            # wait to make sure we can set the url on the pull request
-            kubectl apply -f .kubernetes/qa/webapp.yaml --namespace=${{ env.BRANCH }} --wait=true
-          else
-            kubectl apply -f .kubernetes/qa/webapp.yaml --namespace=${{ env.BRANCH }}
-          fi
+          kubectl apply -f .kubernetes/qa/webapp.yaml --namespace=${{ env.BRANCH }} --wait=true
 
           # assigns the branch image ecr path
           kubectl set image deployment webapp-deployment webapp=${{ env.ECR_PATH }} --record --namespace=${{ env.BRANCH }}
@@ -130,7 +117,24 @@ jobs:
           kubectl set env deployment webapp-deployment NOTHING=$( date "+%Y-%m-%d_%H:%M:%S" ) --namespace=${{ env.BRANCH }}
 
       - name: Set DEPLOYMENT_URL
-        run: echo "DEPLOYMENT_URL=$(kubectl get services webapp-service --namespace=${{ env.BRANCH }} --output jsonpath='{.status.loadBalancer.ingress[0].hostname}')" >> $GITHUB_ENV
+        run: |
+          # zero test
+          timeout=60
+          echo "${{ env.DEPLOYMENT_URL }}"
+          while [ -z "$DEPLOYMENT_URL" ];
+          do
+            DEPLOYMENT_URL=$(kubectl get services webapp-service --namespace=${{ env.BRANCH }} --output jsonpath='{.status.loadBalancer.ingress[0].hostname}')
+            echo "DEPLOYMENT_URL=$DEPLOYMENT_URL" >> $GITHUB_ENV
+
+            ((timeout--))
+
+            if [ "$timeout" == 0 ]; then
+              echo "ERROR: Timeout while waiting for DEPLOYMENT_URL"
+              exit 1
+            fi
+
+            sleep 1;
+          done;
 
       - name: update the github deployment status
         uses: bobheadxi/deployments@v0.5.2
